server:
  port: 8081

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: 12345!@#$%
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

card:
   name: jfoasfjifdasnf
   id: 12

sign:
   app_key:
   app_secret:

youzan:
  token:
    get:
      url: https://open.youzan.com/oauth/token
  client_id: 01320589d05d124004
  client_secret: 1e0bee4b7fcf401f76a8265025e36a7c
  grant_type: silent
  kdt_id: 40036962
scheduled:
  timing: 0 0 01 * * ?
